[2024-12-14 08:20:58 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2024-12-14 08:20:58 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-12-14 08:20:58 +0000] [1] [INFO] Using worker: sync
[2024-12-14 08:20:58 +0000] [20] [INFO] Booting worker with pid: 20
[2024-12-14 08:23:30 +0000] [1] [INFO] Handling signal: term
[2024-12-14 08:23:30 +0000] [20] [INFO] Worker exiting (pid: 20)
[2024-12-14 08:23:30 +0000] [1] [INFO] Shutting down: Master
[2024-12-18 06:38:28 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2024-12-18 06:38:28 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-12-18 06:38:28 +0000] [1] [INFO] Using worker: sync
[2024-12-18 06:38:28 +0000] [20] [INFO] Booting worker with pid: 20
[2024-12-18 06:39:31,912] ERROR in app: Exception on /create_group_room [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/Group/group_app.py", line 57, in create_group_room
    group_data.create_room(id=id, password=password, room_id=room_id)  # ファイル情報を保存
  File "/app/Group/group_data.py", line 37, in create_room
    db_session.execute(query, {"id": id, "password": password, "room_id": room_id})
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 778, in execute
    return self._proxied.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2145, in _execute_internal
    statement = coercions.expect(roles.StatementRole, statement)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 395, in expect
    resolved = impl._literal_coercion(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 621, in _literal_coercion
    return self._text_coercion(element, argname, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 614, in _text_coercion
    return _no_text_coercion(element, argname)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 584, in _no_text_coercion
    raise exc_cls(
sqlalchemy.exc.ArgumentError: Textual SQL expression '\n        INSERT INTO room...' should be explicitly declared as text('\n        INSERT INTO room...')
[2024-12-18 06:39:46 +0000] [1] [INFO] Handling signal: term
[2024-12-18 06:39:46 +0000] [20] [INFO] Worker exiting (pid: 20)
[2024-12-18 06:39:46 +0000] [1] [INFO] Shutting down: Master
[2024-12-18 06:55:54 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2024-12-18 06:55:54 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-12-18 06:55:54 +0000] [1] [INFO] Using worker: sync
[2024-12-18 06:55:54 +0000] [20] [INFO] Booting worker with pid: 20
[2024-12-18 07:00:51 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:20)
[2024-12-18 07:00:51 +0000] [20] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-12-18 07:00:51 +0000] [20] [INFO] Worker exiting (pid: 20)
[2024-12-18 07:00:52 +0000] [21] [INFO] Booting worker with pid: 21
[2024-12-18 07:08:20 +0000] [1] [INFO] Handling signal: term
[2024-12-18 07:08:20 +0000] [21] [INFO] Worker exiting (pid: 21)
[2024-12-18 07:08:20 +0000] [1] [INFO] Shutting down: Master
[2024-12-18 07:08:30 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2024-12-18 07:08:30 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-12-18 07:08:30 +0000] [1] [INFO] Using worker: sync
[2024-12-18 07:08:30 +0000] [20] [INFO] Booting worker with pid: 20
[2024-12-18 07:09:18 +0000] [1] [INFO] Handling signal: term
[2024-12-18 07:09:18 +0000] [20] [INFO] Worker exiting (pid: 20)
[2024-12-18 07:09:18 +0000] [1] [INFO] Shutting down: Master
[2024-12-18 07:09:24 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2024-12-18 07:09:24 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-12-18 07:09:24 +0000] [1] [INFO] Using worker: sync
[2024-12-18 07:09:24 +0000] [20] [INFO] Booting worker with pid: 20
[2024-12-18 07:12:35 +0000] [1] [INFO] Handling signal: term
[2024-12-18 07:16:51 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2024-12-18 07:16:51 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-12-18 07:16:51 +0000] [1] [INFO] Using worker: sync
[2024-12-18 07:16:51 +0000] [21] [INFO] Booting worker with pid: 21
[2024-12-18 07:17:49 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:21)
[2024-12-18 07:17:49 +0000] [21] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-12-18 07:17:49 +0000] [21] [INFO] Worker exiting (pid: 21)
[2024-12-18 07:17:49 +0000] [22] [INFO] Booting worker with pid: 22
[2024-12-18 07:18:49 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:22)
[2024-12-18 07:18:49 +0000] [22] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-12-18 07:18:49 +0000] [22] [INFO] Worker exiting (pid: 22)
[2024-12-18 07:18:49 +0000] [23] [INFO] Booting worker with pid: 23
[2024-12-18 07:25:46 +0000] [1] [INFO] Handling signal: term
[2024-12-18 07:25:46 +0000] [23] [INFO] Worker exiting (pid: 23)
[2024-12-18 07:25:46 +0000] [1] [INFO] Shutting down: Master
[2024-12-18 07:33:20 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2024-12-18 07:33:20 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-12-18 07:33:20 +0000] [1] [INFO] Using worker: sync
[2024-12-18 07:33:20 +0000] [21] [INFO] Booting worker with pid: 21
[2024-12-18 07:33:58 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:21)
[2024-12-18 07:33:58 +0000] [21] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-12-18 07:33:58 +0000] [21] [INFO] Worker exiting (pid: 21)
[2024-12-18 07:33:58 +0000] [22] [INFO] Booting worker with pid: 22
[2024-12-18 07:35:06 +0000] [1] [INFO] Handling signal: term
[2024-12-18 07:35:06 +0000] [22] [INFO] Worker exiting (pid: 22)
[2024-12-18 07:35:06 +0000] [1] [INFO] Shutting down: Master
[2024-12-18 07:35:11 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2024-12-18 07:35:11 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-12-18 07:35:11 +0000] [1] [INFO] Using worker: sync
[2024-12-18 07:35:11 +0000] [20] [INFO] Booting worker with pid: 20
[2024-12-18 07:36:43 +0000] [1] [INFO] Handling signal: term
[2024-12-18 07:36:43 +0000] [20] [INFO] Worker exiting (pid: 20)
[2024-12-18 07:36:43 +0000] [1] [INFO] Shutting down: Master
[2024-12-18 07:37:03 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2024-12-18 07:37:03 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-12-18 07:37:03 +0000] [1] [INFO] Using worker: sync
[2024-12-18 07:37:03 +0000] [20] [INFO] Booting worker with pid: 20
[2024-12-18 07:38:16 +0000] [1] [INFO] Handling signal: term
[2024-12-18 07:38:16 +0000] [20] [INFO] Worker exiting (pid: 20)
[2024-12-18 07:38:16 +0000] [1] [INFO] Shutting down: Master
[2024-12-18 07:44:21 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2024-12-18 07:44:21 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-12-18 07:44:21 +0000] [1] [INFO] Using worker: sync
[2024-12-18 07:44:21 +0000] [18] [INFO] Booting worker with pid: 18
[2024-12-18 07:51:03 +0000] [1] [INFO] Handling signal: term
[2024-12-18 07:51:03 +0000] [18] [INFO] Worker exiting (pid: 18)
[2024-12-18 07:51:03 +0000] [1] [INFO] Shutting down: Master
[2024-12-18 07:51:47 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2024-12-18 07:51:47 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-12-18 07:51:47 +0000] [1] [INFO] Using worker: sync
[2024-12-18 07:51:47 +0000] [20] [INFO] Booting worker with pid: 20
[2024-12-18 07:51:48 +0000] [20] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/app.py", line 8, in <module>
    import fs_data  # ファイルやデータを管理するモジュール --- (*1)
  File "/app/fs_data.py", line 6, in <module>
    import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
[2024-12-18 07:51:48 +0000] [20] [INFO] Worker exiting (pid: 20)
[2024-12-18 07:51:48 +0000] [1] [ERROR] Worker (pid:20) exited with code 3
[2024-12-18 07:51:48 +0000] [1] [ERROR] Shutting down: Master
[2024-12-18 07:51:48 +0000] [1] [ERROR] Reason: Worker failed to boot.
[2024-12-18 07:55:01 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2024-12-18 07:55:01 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-12-18 07:55:01 +0000] [1] [INFO] Using worker: sync
[2024-12-18 07:55:01 +0000] [20] [INFO] Booting worker with pid: 20
[2024-12-18 07:56:59 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:20)
[2024-12-18 07:56:59 +0000] [20] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-12-18 07:56:59 +0000] [20] [INFO] Worker exiting (pid: 20)
[2024-12-18 07:57:00 +0000] [21] [INFO] Booting worker with pid: 21
[2024-12-18 07:57:48 +0000] [1] [INFO] Handling signal: term
[2024-12-18 07:57:48 +0000] [21] [INFO] Worker exiting (pid: 21)
[2024-12-18 07:57:48 +0000] [1] [INFO] Shutting down: Master
[2024-12-18 07:59:03 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2024-12-18 07:59:03 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-12-18 07:59:03 +0000] [1] [INFO] Using worker: sync
[2024-12-18 07:59:03 +0000] [20] [INFO] Booting worker with pid: 20
[2024-12-18 07:59:25 +0000] [1] [INFO] Handling signal: term
[2024-12-18 07:59:25 +0000] [20] [INFO] Worker exiting (pid: 20)
[2024-12-18 07:59:25 +0000] [1] [INFO] Shutting down: Master
[2024-12-18 08:00:47 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2024-12-18 08:00:47 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-12-18 08:00:47 +0000] [1] [INFO] Using worker: sync
[2024-12-18 08:00:47 +0000] [20] [INFO] Booting worker with pid: 20
[2024-12-18 08:02:49 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2024-12-18 08:02:49 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-12-18 08:02:49 +0000] [1] [INFO] Using worker: sync
[2024-12-18 08:02:49 +0000] [20] [INFO] Booting worker with pid: 20
[2024-12-18 08:03:42 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:20)
[2024-12-18 08:03:42 +0000] [20] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-12-18 08:03:42 +0000] [20] [INFO] Worker exiting (pid: 20)
[2024-12-18 08:03:42 +0000] [21] [INFO] Booting worker with pid: 21
[2024-12-18 08:06:50 +0000] [1] [INFO] Handling signal: term
[2024-12-18 08:06:50 +0000] [21] [INFO] Worker exiting (pid: 21)
[2024-12-18 08:06:50 +0000] [1] [INFO] Shutting down: Master
[2024-12-18 08:07:17 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2024-12-18 08:07:17 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-12-18 08:07:17 +0000] [1] [INFO] Using worker: sync
[2024-12-18 08:07:17 +0000] [21] [INFO] Booting worker with pid: 21
[2024-12-18 08:07:42 +0000] [1] [INFO] Handling signal: term
[2024-12-18 08:07:42 +0000] [21] [INFO] Worker exiting (pid: 21)
[2024-12-18 08:07:43 +0000] [1] [INFO] Shutting down: Master
[2024-12-19 04:54:06 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2024-12-19 04:54:06 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-12-19 04:54:06 +0000] [1] [INFO] Using worker: sync
[2024-12-19 04:54:06 +0000] [20] [INFO] Booting worker with pid: 20
[2024-12-19 04:56:04 +0000] [1] [INFO] Handling signal: term
[2024-12-19 04:56:04 +0000] [20] [INFO] Worker exiting (pid: 20)
[2024-12-19 04:56:04 +0000] [1] [INFO] Shutting down: Master
